import axios from 'axios';

export const queryAnalysis = async (req, res) => {
  try {
    const { query, fileId } = req.body;

    if (!query || !fileId) {
      return res.status(400).json({ success: false, message: 'Missing query or fileId' });
    }

    const { File } = await import('../models/File.js');
    const file = await File.findOne({ _id: fileId, userId: req.user._id });

    if (!file) {
      return res.status(404).json({ success: false, message: 'File not found' });
    }

    // TODO: Call AI API to process query
    // For now, return mock data

    res.json({
      success: true,
      results: {
        query,
        analysis: 'Analysis results will be generated by AI',
        charts: [],
        insights: 'Insights will be generated by AI',
      },
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const saveDashboard = async (req, res) => {
  try {
    const { name, fileId, charts, insights } = req.body;
    const { Dashboard } = await import('../models/Dashboard.js');

    const dashboard = new Dashboard({
      name,
      userId: req.user._id,
      fileId,
      charts,
      insights,
    });

    await dashboard.save();

    res.status(201).json({
      success: true,
      message: 'Dashboard saved successfully',
      dashboard,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};

export const getDashboards = async (req, res) => {
  try {
    const { Dashboard } = await import('../models/Dashboard.js');
    const dashboards = await Dashboard.find({ userId: req.user._id }).sort({ createdAt: -1 });

    res.json({
      success: true,
      dashboards,
    });
  } catch (error) {
    res.status(500).json({ success: false, message: error.message });
  }
};
